# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkin.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcheckin.proto\x12\x07protopy\"\x17\n\x07\x43heckin\x12\x0c\n\x04type\x18\x0c \x01(\t\"D\n\x0e\x43heckinRequest\x12!\n\x07\x63heckin\x18\x04 \x01(\x0b\x32\x10.protopy.Checkin\x12\x0f\n\x07version\x18\x0e \x01(\x05\"=\n\x0f\x43heckinResponse\x12\x12\n\nandroid_id\x18\x07 \x01(\x06\x12\x16\n\x0esecurity_token\x18\x08 \x01(\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkin_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKIN._serialized_start=26
  _CHECKIN._serialized_end=49
  _CHECKINREQUEST._serialized_start=51
  _CHECKINREQUEST._serialized_end=119
  _CHECKINRESPONSE._serialized_start=121
  _CHECKINRESPONSE._serialized_end=182
# @@protoc_insertion_point(module_scope)
